# ═══════════════════════════════════════════════════════════════════════════
#  bonds.jl — bond lists for the exact-diagonalization engine.
#
#  Extracted from the legacy two_magnon_basis_3D.jl.  Site indexing is
#
#      s(ix,iy,iz) = ix + (iy-1)Nx + (iz-1)Nx Ny,   ix ∈ 1:Nx, ...
#
#  which is the same convention as `site_coords` in ed_gamma.jl; the two are
#  checked against each other by `gamma_check_site_convention`.
# ═══════════════════════════════════════════════════════════════════════════

@inline xyz_to_site(ix::Int, iy::Int, iz::Int, Nx::Int, Ny::Int, Nz::Int) =
    mod1(ix, Nx) + (mod1(iy, Ny) - 1) * Nx + (mod1(iz, Nz) - 1) * Nx * Ny

"""
    bonds_from_offsets_3d(Nx, Ny, Nz, offsets) -> Vector{Tuple{Int,Int}}

Every unordered bond generated by the grid offsets `(Δix,Δiy,Δiz)`, one per
site, periodic in all three directions.  A self-bond (offset aliasing to zero
on the torus) is an error.
"""
function bonds_from_offsets_3d(Nx::Int, Ny::Int, Nz::Int, offsets)
    bonds = Tuple{Int,Int}[]
    sizehint!(bonds, length(offsets) * Nx * Ny * Nz)
    for iz in 1:Nz, iy in 1:Ny, ix in 1:Nx
        s = xyz_to_site(ix, iy, iz, Nx, Ny, Nz)
        for (dx, dy, dz) in offsets
            t = xyz_to_site(ix + dx, iy + dy, iz + dz, Nx, Ny, Nz)
            s == t && error("self-bond: offset ($dx,$dy,$dz) maps a site to " *
                            "itself on a $Nx×$Ny×$Nz torus; use a larger lattice")
            push!(bonds, (s, t))
        end
    end
    return bonds
end

"""
    shell_bonds(Nx, Ny, Nz, δ) -> Vector{Tuple{Int,Int}}

Bonds of the single shell `±δ`.  Errors unless `+δ` and `-δ` are distinct
lattice vectors, `2|δ_d| < L_d`, which is the same aliasing condition the LS
solvers impose on their mesh.
"""
function shell_bonds(Nx::Int, Ny::Int, Nz::Int, δ::NTuple{3,Int})
    L = (Nx, Ny, Nz)
    for d in 1:3
        2*abs(δ[d]) < L[d] || δ[d] == 0 ||
            error("shell $δ aliases along direction $d on a $Nx×$Ny×$Nz " *
                  "torus: need 2|δ| < L, got 2·$(abs(δ[d])) ≥ $(L[d])")
    end
    return bonds_from_offsets_3d(Nx, Ny, Nz, [δ])
end
